version: '3.8'

services:
  comments-api:
    build: ./comments-api
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      - PORT=${EXTERNAL_PORT}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - TELEGRAM_NOTIFY_URL=${TELEGRAM_NOTIFY_URL:-http://localhost:8080/notify}
    depends_on:
      - mongo
    networks:
      - comments-net
    restart: unless-stopped

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - comments-net
    restart: unless-stopped

networks:
  comments-net:


volumes:
  mongo_data:
